language: c

before_script:
  - git clone https://github.com/libharu/libharu
  - cd libharu
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install


compiler:
  - clang
  - gcc

script: make
